mod active_window;
mod battery;
mod clock;
mod cpu_load;
mod kb_layout;
mod memory_usage;
mod network;
mod workspaces;
pub use active_window::build_active_window;
pub use battery::build_battery;
pub use clock::build_clock;
pub use cpu_load::build_cpu_load;
pub use kb_layout::build_keyboard_label;
pub use memory_usage::build_memory_usage;
pub use network::build_network;
pub use workspaces::build_workspaces;
